version: "3"
services:
    database:
        image: "postgres" # use latest official postgres version
        env_file:
            - database.env # configure postgres
        volumes:
            - data:/var/lib/postgresql/data/ # persist data even if container shuts down volumes:
        ports:
            - 5432:5432
volumes:
    data: # named volumes can be managed easier using docker-compose
